### ISSUE TITLE
Release 2015.12 - RC4

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/Release-Specs#16] opened 2016-01-08 02:14 UTC
Status of all tests for the [Release Candidate 4](https://github.com/RIOT-OS/RIOT/tree/2015.12-RC4) of the 2015.12 release.

Please check off all tests that performed successfully. Inline any errors/warnings you encounter in this list.
The names I assigned are tentative. Feel free to re-assign or execute tests that are not marked with your name.

- [x] [01-CI](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/01-ci.md) @cgundogan @thomaseichinger (OS X)
 - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/01-ci.md#task-01)
 - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/01-ci.md#task-02)
 - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/01-ci.md#task-03)
 - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/01-ci.md#task-04)
- [ ] [02-Tests](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/02-tests.md) @A-Paul @thomaseichinger (OS X) (see https://github.com/RIOT-OS/Release-Specs/issues/17 for details)
 - [ ] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/02-tests.md#task-01)
 - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/02-tests.md#task-02)
 - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/02-tests.md#task-03)
- [x] [03-Single Hop IPv6 ICMP](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/03-single-hop-ipv6-icmp.md) @PeterKietzmann
 - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/03-single-hop-ipv6-icmp.md#task-01)
 - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/03-single-hop-ipv6-icmp.md#task-02)
 - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/03-single-hop-ipv6-icmp.md#task-03)
- [x] [04-Single Hop 6LoWPAN ICMP](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/04-single-hop-6lowpan-icmp.md) @authmillenon 
 - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/04-single-hop-6lowpan-icmp.md#task-01)
 - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/04-single-hop-6lowpan-icmp.md#task-02)
 - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/04-single-hop-6lowpan-icmp.md#task-03)
 - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/04-single-hop-6lowpan-icmp.md#task-04)
- [x] [05-Single Hop Route](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/05-single-hop-route.md) @authmillenon 
 - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/05-single-hop-route.md#task-01)
 - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/05-single-hop-route.md#task-02)
 - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/05-single-hop-route.md#task-03)
- [x] [06-Single Hop UDP](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/06-single-hop-udp.md) @haukepetersen 
- [x] [07-Multi Hop](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/07-multi-hop.md) @cgundogan
 - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/07-multi-hop.md#task-01)
 - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/07-multi-hop.md#task-02)
 - [x] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/07-multi-hop.md#task-03)
 - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/07-multi-hop.md#task-04)
- [ ] [08-Interop](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/08-interop.md) @OlegHahm 
 - [x] [Task 01](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/08-interop.md#task-01)
 - [x] [Task 02](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/08-interop.md#task-02)
 - [ ] [Task 03](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/08-interop.md#task-03)
 - [x] [Task 04](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/08-interop.md#task-04)
 - [x] [Task 05](https://github.com/RIOT-OS/Release-Specs/blob/master/specs/2015-12/08-interop.md#task-05)

**Comment by authmillenon** [comment] 2016-01-08 03:12
I'm testing 06 with the following patch:

```diff
diff --git a/examples/gnrc_networking/Makefile b/examples/gnrc_networking/Makefile
index 30bb5ee..81e2804 100644
--- a/examples/gnrc_networking/Makefile
+++ b/examples/gnrc_networking/Makefile
@@ -21,13 +21,12 @@ USEMODULE += gnrc_ipv6_router_default
 USEMODULE += gnrc_udp
 # Add a routing protocol
 USEMODULE += gnrc_rpl
-# This application dumps received packets to STDIO using the pktdump module
-USEMODULE += gnrc_pktdump
 # Additional networking modules that can be dropped if not needed
 USEMODULE += gnrc_icmpv6_echo
 # Add also the shell, some shell commands
 USEMODULE += shell
 USEMODULE += shell_commands
+USEMODULE += od
 USEMODULE += ps
 
 # Comment this out to disable code in RIOT that does safety checking
diff --git a/examples/gnrc_networking/udp.c b/examples/gnrc_networking/udp.c
index af10651..4d56ac1 100644
--- a/examples/gnrc_networking/udp.c
+++ b/examples/gnrc_networking/udp.c
@@ -22,22 +22,68 @@
 #include <inttypes.h>
 
 #include "kernel.h"
+#include "msg.h"
 #include "net/gnrc.h"
 #include "net/gnrc/ipv6.h"
 #include "net/gnrc/udp.h"
-#include "net/gnrc/pktdump.h"
+#include "thread.h"
 #include "timex.h"
 #include "xtimer.h"
 
+#define SERVER_MSG_QUEUE_SIZE   (8U)
+#define SERVER_PRIO             (THREAD_PRIORITY_MAIN - 1)
+#define SERVER_STACKSIZE        (THREAD_STACKSIZE_MAIN)
+
 static gnrc_netreg_entry_t server = { NULL, GNRC_NETREG_DEMUX_CTX_ALL, KERNEL_PID_UNDEF };
+static char server_stack[SERVER_STACKSIZE];
+static msg_t server_queue[SERVER_MSG_QUEUE_SIZE];
+static kernel_pid_t server_pid = KERNEL_PID_UNDEF;
+static uint8_t send_count = 0;
+
+static void *_eventloop(void *arg)
+{
+    (void)arg;
+    msg_t msg, reply;
+    unsigned int rcv_count = 0, snd_count = 0;
+
+    /* setup the message queue */
+    msg_init_queue(server_queue, SERVER_MSG_QUEUE_SIZE);
+
+    reply.content.value = (uint32_t)(-ENOTSUP);
+    reply.type = GNRC_NETAPI_MSG_TYPE_ACK;
+
+    while (1) {
+        msg_receive(&msg);
+
+        switch (msg.type) {
+            case GNRC_NETAPI_MSG_TYPE_RCV:
+                printf("Packets received: %d\n", ++rcv_count);
+                gnrc_pktbuf_release((gnrc_pktsnip_t *)msg.content.ptr);
+                break;
+            case GNRC_NETAPI_MSG_TYPE_SND:
+                printf("Packets send: %d\n", ++snd_count);
+                gnrc_pktbuf_release((gnrc_pktsnip_t *)msg.content.ptr);
+                break;
+            case GNRC_NETAPI_MSG_TYPE_GET:
+            case GNRC_NETAPI_MSG_TYPE_SET:
+                msg_reply(&msg, &reply);
+                break;
+            default:
+                break;
+        }
+    }
 
+    /* never reached */
+    return NULL;
+}
 
-static void send(char *addr_str, char *port_str, char *data, unsigned int num,
+static void send(char *addr_str, char *port_str, char *data_len_str, unsigned int num,
                  unsigned int delay)
 {
     uint8_t port[2];
     uint16_t tmp;
     ipv6_addr_t addr;
+    size_t data_len;
 
     /* parse destination address */
     if (ipv6_addr_from_str(&addr, addr_str) == NULL) {
@@ -53,14 +99,21 @@ static void send(char *addr_str, char *port_str, char *data, unsigned int num,
     port[0] = (uint8_t)tmp;
     port[1] = tmp >> 8;
 
+    data_len = (size_t)atoi(data_len_str);
+    if (data_len == 0) {
+        puts("Error: unable to parse data_len");
+        return;
+    }
+
     for (unsigned int i = 0; i < num; i++) {
         gnrc_pktsnip_t *payload, *udp, *ip;
         /* allocate payload */
-        payload = gnrc_pktbuf_add(NULL, data, strlen(data), GNRC_NETTYPE_UNDEF);
+        payload = gnrc_pktbuf_add(NULL, NULL, data_len, GNRC_NETTYPE_UNDEF);
         if (payload == NULL) {
             puts("Error: unable to copy data to packet buffer");
             return;
         }
+        memset(payload->data, send_count++, data_len);
         /* allocate UDP header, set source port := destination port */
         udp = gnrc_udp_hdr_build(payload, port, 2, port, 2);
         if (udp == NULL) {
@@ -103,8 +156,16 @@ static void start_server(char *port_str)
         puts("Error: invalid port specified");
         return;
     }
+    if (server_pid <= KERNEL_PID_UNDEF) {
+        server_pid = thread_create(server_stack, sizeof(server_stack), SERVER_PRIO,
+                                   THREAD_CREATE_STACKTEST, _eventloop, NULL, "UDP server");
+        if (server_pid <= KERNEL_PID_UNDEF) {
+            puts("Error: can not start server thread");
+            return;
+        }
+    }
     /* start server (which means registering pktdump for the chosen port) */
-    server.pid = gnrc_pktdump_getpid();
+    server.pid = server_pid;
     server.demux_ctx = (uint32_t)port;
     gnrc_netreg_register(GNRC_NETTYPE_UDP, &server);
     printf("Success: started UDP server on port %" PRIu16 "\n", port);
```

**Comment by authmillenon** [comment] 2016-01-08 03:30
Unittests tested on Ubuntu Trusty.

**Comment by cgundogan** [comment] 2016-01-08 07:56
> I'm testing 06 with the following patch:

FYI: there is a PR (#15) from @haukepetersen that tests 06. (The 07 in the PR is meant to be 06)

**Comment by OlegHahm** [comment] 2016-01-08 12:44
If no-one knows how to setup a Contiki test, I declare Interop tests hereby as successful.

**Comment by A-Paul** [comment] 2016-01-08 13:13
I will start going through *02-Tests Task 1* now.

**Comment by authmillenon** [comment] 2016-01-08 14:14
@A-Paul https://github.com/RIOT-OS/RIOT/pull/4623 might be of interest for you, regarding `conn_ip` ;-).

**Comment by cgundogan** [comment] 2016-01-08 15:17
@A-Paul did you encounter any new errors/warnings so far?

**Comment by A-Paul** [comment] 2016-01-08 15:52
@cgundogan sorry for letency. :-) I was concentrated going through all tests with a script and making notes for later.

For now:
+ fault_handler (memory error)
+ msg_send_recieve ("Test failed.")

**Comment by cgundogan** [comment] 2016-01-08 16:16
@A-Paul the `msg_send_receive` issue should be fixed with RIOT-OS/RIOT#4620 (:

**Comment by A-Paul** [comment] 2016-01-08 17:43
> @A-Paul the msg_send_receive issue should be fixed with RIOT-OS/RIOT#4620 (:

Confirmed.

**Comment by A-Paul** [comment] 2016-01-08 19:58
So far most is fine. *conn_ip, unittests and zep* are stil TODO.

**Comment by cgundogan** [comment] 2016-01-10 15:49
closing, because the 2015.12 version of RIOT was released.

**Closed by cgundogan** 2016-01-10 15:49 UTC
Labels: help wanted
